# Generated by Django 4.2.13 on 2024-07-09 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result1', models.IntegerField(blank=True)),
                ('result2', models.IntegerField(blank=True)),
                ('result3', models.IntegerField(blank=True)),
                ('result4', models.IntegerField(blank=True)),
                ('result5', models.IntegerField(blank=True)),
                ('result6', models.IntegerField(blank=True)),
                ('result7', models.IntegerField(blank=True)),
                ('result8', models.IntegerField(blank=True)),
                ('result9', models.IntegerField(blank=True)),
                ('result10', models.IntegerField(blank=True)),
                ('result11', models.IntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
